version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
          - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/retromasterdb?allowPublicKeyRetrieval=true&useSSL=false
          - SPRING_DATASOURCE_DRIVER=com.mysql.cj.jdbc.Driver
          - SPRING_DATASOURCE_USERNAME=root
          - SPRING_DATASOURCE_PASSWORD=root
          - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - retromaster-network
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: retromasterdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - retromaster-network

volumes:
  mysql_data:

networks:
  retromaster-network:
     